# SCREEN_WIDTH = 1000
# SCREEN_HEIGHT = 650
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Kayzee"

CHARACTER_SCALING = 0.21
TILE_SCALING = 0.5
COIN_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

MOVEMENT_SPEED = 7
GRAVITY = 1
JUMP_SPEED = 20

LEFT_VIEWPORT_MARGIN = 300
RIGHT_VIEWPORT_MARGIN = 300
TOP_VIEWPORT_MARGIN = 100
BOTTOM_VIEWPORT_MARGIN = 60

PLAYER_START_X = 128
PLAYER_START_Y = 128

BULLET_SPEED = 8
BULLET_SCALE = 0.8

FACE_RIGHT = 1
FACE_LEFT = 2
FACE_UP = 3
FACE_DOWN = 4

ENEMY_SCALE = 0.5
ENEMY_SPEED = 4
